### ISSUE TITLE
Running RnBeads in a computing cluster (Ghostscript needed?)

### ISSUE THREAD

**Issue by samuel-carleial** [epigen/RnBeads#11]
Hi,

I am interested in running some tests with my data using RnBeads. I am using the cluster system provided by the State of Baden-Württemberg and I could set up all packages and files. However, is ghostscript needed?

I would be really glad to have a template R script that I could work upon and adjust for my needs. Is there any reference on your website?

Thank you very much for the help!

**Comment by schmic05** [comment]
Hi @samuel-carleial 

Yes, ghostscript should always be installed, please see our website for further information (https://rnbeads.org/installation.html). We recommend that you install RnBeads using our installation script on the website using:
`source("http://rnbeads.org/data/install.R")`
For the cluster system it depends very much on the Job Scheduling System that you use. We currently support Sun Grid Engine and SLURM, but RnBeads could be extended to further systems. You'll have to create an XML file specifying the options and then an R script to start the analysis. Which Scheduling System is used in your setting?

**Comment by samuel-carleial** [comment]
Exactly, we use the SLURM scheduler. And the setting up of RnBeads is done.
I am running some tests, and it is seems to be working. My worry is only that at the end it will be saved in the HTML report.

**Comment by schmic05** [comment]
Alright, let me know if you need anything more.

**Comment by samuel-carleial** [comment]
This is the result I got:

```
...
Error in save.rnb.diffmeth(diffmeth, diffmeth.path) : 
  trying to get slot "disk.dump" from an object of a basic class ("NULL") with no slots
Calls: rnb.run.analysis -> rnb.run.differential -> save.rnb.diffmeth
In addition: Warning messages:
1: Removed 2558 rows containing non-finite values (stat_density). 
2: Removed 2558 rows containing non-finite values (stat_density). 
Execution halted
```

I am running this job after loading these and using R 3.6.3:

```
Loading module dependency 'compiler/intel/19.1'.
Loading module dependency 'numlib/mkl/2020'.
```

**Comment by schmic05** [comment]
This is a typical error that occurs when the grouping information in your differential analysis is not well defined. There should be something like this "Invalid grouping information, returning NULL" in your log file.
Please check the following options:

- differential.comparison.columns
- min.group.size
- max.group.count

**Comment by samuel-carleial** [comment]
It worked! I just need to do the fine-tunning now!

Thank you again!
