### ISSUE TITLE
Bug on LOLA

### ISSUE THREAD

**Issue by pietrisko** [epigen/RnBeads#21]
Hi,

I'm trying to run LOLA within RnBeads but I always get an error like this or similar:

![image](https://user-images.githubusercontent.com/44844060/112167534-d1035300-8bf0-11eb-8f5f-21a5e32d2955.png)

**Comment by schmic05** [comment]
Hi @pietrisko 
I never encountered a similar error and it's hard to track down the issue without having something to reproduce it. Might it be that you are running into a memory issue? Otherwise, it would be great if you could share some file with us such that we can reproduce the error.

**Comment by pietrisko** [comment]
Hi,

I have TBs of RAM, the data are unpublished, the strage thing is that the error it is not always the same, sometimes it's 'Error in f__[origorder]' or 'segmentation error' or something similar, but I agree that seems a memory issue, they are only 14 samples from 450K

**Comment by pietrisko** [comment]
Running the analysis on other server solved my issue
