### ISSUE TITLE
Problems during EPIC array preprocessing - normalization step

### ISSUE THREAD

**Issue by justannwska** [epigen/RnBeads#26]
Hi RnBeads team,

I'm consistently encountering this error during pre-processing of EPIC arrays.

Error in dataset@M[, i] <- results[[i]][[1]] : 
  number of items to replace is not a multiple of replacement length

I'm fairly sure that the methylation data was imported. QC worked perfectly. I should add that the error appears during the normalization step (bmiq and enmix.oob). I'm using RnBeads version 2.8.1. I've tried both options with disk.dump.big.matrices = false and true during the data import.

Any ideas what could have gone wrong?

**Comment by demuellae** [comment]
closed due to inactivity
