### ISSUE TITLE
get.table and Cg_id??

### ISSUE THREAD

**Issue by ClarissaFeuersteinAkgoz** [epigen/RnBeads#27]
Nice adding would be the following: 
when you use the function get.table()
`dframe <- get.table(rnb.differential,get.comparisons(rnb.differential)[1], "sites", return.data.frame=TRUE)`
it would be nice to keep the CpG id as a rowname or as information in a column to facilitate downstream processing.

**Comment by demuellae** [comment]
closed due to inactivity
