### ISSUE TITLE
R Error in h(simpleError(msg， call))

### ISSUE THREAD

**Issue by mumdark** [epigen/RnBeads#44]
Hello, I want to report that when I'm running the analysis, I'm getting the following error:

> Error in h(simpleError(msg， call)) : Error evaluating 'x' argument while selecting method for 'which' function: length = 12  in coercion to'logica1(1)

I see the cause of this error [here](https://stackoverflow.com/questions/72848442/r-warning-lengthx-2-1-in-coercion-to-logical1). 

Is there any solution?

Thank you for your help!

**Comment by schmic05** [comment]
Hi @mumdark 
Thank you for using RnBeads. From what you report, I cannot reproduce the error. Can you please share some more information with us, such as the full analysis.log and the code you were running?

Best,

Michael

**Comment by mumdark** [comment]
Thanks for your reply, I use this code to perform the analysis:

>rnb.run.analysis


- Example dataset: Nazor, et al. (2012). Cell Stem Cell, 10(5), 620–634

**When I downgraded the r version, this problem was solved.**

**Comment by schmic05** [comment]
Hi @mumdark ,

Sorry for the delay in coming back to this issue. We fixed it in the current version of RnBeads on Bioconductor, feel free to test it.

Best,

Michael
