### ISSUE TITLE
Question on import methylation intensity

### ISSUE THREAD

**Issue by yeswzc** [epigen/RnBeads#8]
Hi,
Do anyone know how to import methylation intensity signal matrix as a RnBeads or methylumi object? 
I have a matrix with columns as samples with their "Methylated Signal", "Unmethylated Signal" and "Detection Pval" downloaded from GEO database. The raw idat files were not available so I have to start from the intensity signals.  
Is there a function can be used to import the data so that I can use other functions in methylumi to normalize the data?

Thank you!

**Comment by schmic05** [comment]
Hi.
I think the constructor for RnBeadRawSet is what you are searching for. Once you creating this object using the M and U arguments, you can use all of RnBeads' functionality on this object.
Check out the documentation using ?RnBeadRawSet

**Comment by yeswzc** [comment]
Thank you!
I found the usage of RnBeadRawSet requires "pheno" matrix as input. Do you know what is "pheno" and how can I creat the "pheno" matrix?
```
RnBeadRawSet(pheno, probes, M, U, M0 = NULL, U0 = NULL,
bead.counts.M = NULL, bead.counts.U = NULL, p.values = NULL,
qc = NULL, platform = "450k", beta.offset = 100,
summarize.bead.counts = TRUE, summarize.regions = TRUE,
region.types = rnb.region.types.for.analysis("hg19"),
useff = rnb.getOption("disk.dump.big.matrices"), ffcleanup = FALSE)
```

**Comment by yeswzc** [comment]
Thanks.
I found an example of the pheno matrix.
```
Sample_ID Sentrix_ID Sentrix_Position   Sample_Plate Sample_Well Sample_Group  Cell_Line Passage_No Treatment           barcode
```
Some column can be ignored.

Best.

**Comment by yeswzc** [comment]
When imported by RnBeadRawSet(), do you know how can I used method in RnBeads to normalize the data?
I get error below:
```
Warning: Incompatible dataset and normalization method: missing data on quality control probes. Changed the method to "none"
```
Thanks!

**Comment by schmic05** [comment]
It don't see an error in your above output. The message that you see is the summary of the new object that has been created. You will have to show me the actual error message that is printed during the normalization process. Perhaps it helps to change the normalization method using rnb.options(normalization.method="wm.dasen").

**Comment by yeswzc** [comment]
Sorry. My fault. There is no error.
Is there a way to **background correct** the RnBeadRawSet and **normalize** it using functions in methylumi method? Seems the data do not have the required information?

Thank you!

**Comment by schmic05** [comment]
Yes, RnBeads supports some of the normalization methods available in methylumi, see the documentation of ?rnb.execute.normalization for further information. 
As the names suggest, you will also need to have intensity information about the background control probes on the Illumina arrays to perform background correction.

**Comment by yeswzc** [comment]
Understand now. Thanks you!
